// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCulFvj0z8sS9SGi6177sbce6xh7vceIyA',
    appId: '1:999601815280:android:b57b285f09487cd30b8c35',
    messagingSenderId: '999601815280',
    projectId: 'mortar-stage',
    storageBucket: 'mortar-stage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLdLrBc5QGWgqS6w7tuiAsTsof_4nHTu8',
    appId: '1:999601815280:ios:c553e9e0350583920b8c35',
    messagingSenderId: '999601815280',
    projectId: 'mortar-stage',
    storageBucket: 'mortar-stage.firebasestorage.app',
    iosBundleId: 'com.expansionnetwork.expansionNetwork',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUJreREmYaNjbv7zlLLkdTNk-tiFODwA8',
    appId: '1:999601815280:web:ea9680e90fc149160b8c35',
    messagingSenderId: '999601815280',
    projectId: 'mortar-stage',
    authDomain: 'mortar-stage.firebaseapp.com',
    storageBucket: 'mortar-stage.firebasestorage.app',
    measurementId: 'G-XQ2CZ5J7TX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLdLrBc5QGWgqS6w7tuiAsTsof_4nHTu8',
    appId: '1:999601815280:ios:c553e9e0350583920b8c35',
    messagingSenderId: '999601815280',
    projectId: 'mortar-stage',
    storageBucket: 'mortar-stage.firebasestorage.app',
    iosBundleId: 'com.expansionnetwork.expansionNetwork',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUJreREmYaNjbv7zlLLkdTNk-tiFODwA8',
    appId: '1:999601815280:web:4c4ed2e46f9081470b8c35',
    messagingSenderId: '999601815280',
    projectId: 'mortar-stage',
    authDomain: 'mortar-stage.firebaseapp.com',
    storageBucket: 'mortar-stage.firebasestorage.app',
    measurementId: 'G-XN3T0BMWVH',
  );

}