// File generated by FlutterFire CLI, then hand-edited to add environment
// selection. Re-running `flutterfire configure` will overwrite that — re-apply
// the `_env` switch and the `_androidStage` / `_iosStage` blocks if you do.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Which Firebase project the mobile app talks to, set at compile time:
/// `flutter build appbundle --dart-define=FIREBASE_ENV=stage`.
///
/// Defaults to `dev` so an ordinary `flutter run` is unchanged. The native
/// side reads `android/app/google-services.json` instead of this file, so the
/// two must be swapped together — use `tool/build_stage_aab.ps1`, which does
/// both, rather than setting this by hand.
const String _env = String.fromEnvironment('FIREBASE_ENV', defaultValue: 'dev');

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// True when this binary was compiled against `mortar-stage`.
  static bool get isStage => _env == 'stage';

  /// Firebase project the running binary is pointed at, for diagnostics.
  static String get projectId => currentPlatform.projectId;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// An unrecognised `FIREBASE_ENV` throws rather than falling back to dev: a
  /// beta build quietly pointed at the wrong project is worse than one that
  /// refuses to start.
  static Never _unknownEnv() => throw UnsupportedError(
        'Unknown FIREBASE_ENV "$_env". Expected "dev" or "stage".',
      );

  static FirebaseOptions get android => switch (_env) {
        'dev' => _androidDev,
        'stage' => _androidStage,
        _ => _unknownEnv(),
      };

  static FirebaseOptions get ios => switch (_env) {
        'dev' => _iosDev,
        'stage' => _iosStage,
        _ => _unknownEnv(),
      };

  static const FirebaseOptions _androidDev = FirebaseOptions(
    apiKey: 'AIzaSyC7SOdcffz1OKa_sdhG_f-irSlzSmRh4lA',
    appId: '1:260497170681:android:1aef05688db81f66990228',
    messagingSenderId: '260497170681',
    projectId: 'mortar-dev',
    storageBucket: 'mortar-dev.firebasestorage.app',
  );

  static const FirebaseOptions _androidStage = FirebaseOptions(
    apiKey: 'AIzaSyCulFvj0z8sS9SGi6177sbce6xh7vceIyA',
    appId: '1:999601815280:android:b57b285f09487cd30b8c35',
    messagingSenderId: '999601815280',
    projectId: 'mortar-stage',
    storageBucket: 'mortar-stage.firebasestorage.app',
  );

  static const FirebaseOptions _iosDev = FirebaseOptions(
    apiKey: 'AIzaSyB3oL4t6QTlQCBCF4vIEFslbt_WOZKrmJM',
    appId: '1:260497170681:ios:e2762b5675c4ea1e990228',
    messagingSenderId: '260497170681',
    projectId: 'mortar-dev',
    storageBucket: 'mortar-dev.firebasestorage.app',
    iosClientId: '260497170681-0s8m0ahhv9j03ao1dnl1hd9r57dkbvtc.apps.googleusercontent.com',
    iosBundleId: 'com.mortar.wearemortar',
  );

  // No iosClientId: mortar-stage's iOS app has no OAuth client configured, so
  // Google Sign-In is unavailable on a stage iOS build until one is added.
  static const FirebaseOptions _iosStage = FirebaseOptions(
    apiKey: 'AIzaSyBLdLrBc5QGWgqS6w7tuiAsTsof_4nHTu8',
    appId: '1:999601815280:ios:2b17fdc1272dca230b8c35',
    messagingSenderId: '999601815280',
    projectId: 'mortar-stage',
    storageBucket: 'mortar-stage.firebasestorage.app',
    iosBundleId: 'com.mortar.wearemortar',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUJreREmYaNjbv7zlLLkdTNk-tiFODwA8',
    appId: '1:999601815280:web:ea9680e90fc149160b8c35',
    messagingSenderId: '999601815280',
    projectId: 'mortar-stage',
    authDomain: 'mortar-stage.firebaseapp.com',
    storageBucket: 'mortar-stage.firebasestorage.app',
    measurementId: 'G-XQ2CZ5J7TX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLdLrBc5QGWgqS6w7tuiAsTsof_4nHTu8',
    appId: '1:999601815280:ios:2b17fdc1272dca230b8c35',
    messagingSenderId: '999601815280',
    projectId: 'mortar-stage',
    storageBucket: 'mortar-stage.firebasestorage.app',
    iosBundleId: 'com.mortar.wearemortar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUJreREmYaNjbv7zlLLkdTNk-tiFODwA8',
    appId: '1:999601815280:web:4c4ed2e46f9081470b8c35',
    messagingSenderId: '999601815280',
    projectId: 'mortar-stage',
    authDomain: 'mortar-stage.firebaseapp.com',
    storageBucket: 'mortar-stage.firebasestorage.app',
    measurementId: 'G-XN3T0BMWVH',
  );

}